#membuat program menggunakan string formating
print("hello ini script python")
print("      *       ")
print("     ***      ")
print("    *****     ")
print("   *******    ")
print("  *********   ")
print("   *******    ")
print("    *****     ")
print("     ***      ")
print("      *       ")